---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.qeCIPipelines.defaults.namespace }}-cr
rules:
- apiGroups: ["hive.openshift.io"]
  resources: ["clusterdeployments"]
  verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["managedclustersets/join"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets", "configmaps", "namespaces"]
  verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
- apiGroups: ["hypershift.openshift.io"]
  resources: ["hostedclusters", "nodepools"]
  verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.qeCIPipelines.defaults.namespace }}-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.qeCIPipelines.defaults.namespace }}-cr
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: {{ .Values.qeCIPipelines.defaults.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.qeCIPipelines.defaults.namespace }}-image-puller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: {{ .Values.qeCIPipelines.defaults.namespace }}
{{- if .Values.qeCIPipelines.schedules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.qeCIPipelines.defaults.namespace }}-pipelinerun-trigger
  namespace: {{ .Values.qeCIPipelines.defaults.namespace }}
  labels:
    {{- include "pipelines.labels" . | nindent 4 }}
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["create", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.qeCIPipelines.defaults.namespace }}-pipelinerun-trigger
  namespace: {{ .Values.qeCIPipelines.defaults.namespace }}
  labels:
    {{- include "pipelines.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.qeCIPipelines.defaults.namespace }}-pipelinerun-trigger
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: {{ .Values.qeCIPipelines.defaults.namespace }}
{{- end }}
